#!/usr/bin/env bash
# a script that transfers a file from a client to a server

if [ -z "$4" ];
then
echo "$0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit
fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
