#!/usr/bin/env bash
# a script that configures a server to listen on
# port 80 of all the server’s active IPv4 IPs.
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx start
